
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
  displayName: 'Terraform Init'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Infra'


- script: |
    echo "Logging into Azure portal now.."
    az login --service-principal --username $(uname) --password $(pwd) --tenant $(tenantId)

    echo "Selecting the subscription.."
    az account set --subscription $(subsId)

    echo "showing the account details."
    sleep 10s
    az account show
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Infra'
 

  